nam=input("Enter your name: ")
br=input("Enter your branch: ")
gend=input("Enter your gender: ")
col=input("Enter your college name: ")
age=input("Enter your age: ")
print("NAME: "+nam)
print("COLLEGE NAME: "+col)
print("BRANCH NAME: "+br)
print("GENDER: "+gend)
print("AGE: "+str(age))